[package]
name = "raytracer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
stb_image = "0.2.4"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"